### ISSUE TITLE
[BUG] Driver install has ruined my computer 

### ISSUE THREAD

**Issue by xXGamerAwesomeXx** [Davidobot/BetterJoyForCemu#1200]
**Describe the bug**
After installing the driver and restarting, barely anything opens and most of what remains freezes after a while. Similar thing happens if you start your computer with a vive pro plugged in. I've uninstalled the driver, and deleted the betterjoy folder and cleaned the trashcan with the little bit of time before everything breaks, but nothing changes.

**Expected behavior**
A usable computer

**Controller (please complete the following information):**
 Irrelevant

**Comment by xXGamerAwesomeXx** [comment]
not being even restore points fix this wtf

**Comment by Bigboibigdum** [comment]
not being even restore points fix this wtf

**Comment by Bigboibigdum** [comment]
it's giving constant blue screens, and i think that's because it won't realise a single file exists. I'm going to have to reinstall everything. I'm going to have to lose everything i made for my game. thanks

**Comment by xXGamerAwesomeXx** [comment]
constant blue screens thanks to every file becoming a ghost. I'm going to have to reset my pc and lose everything I've made for a game i was really exited for. it was hard getting this started, I'm not going to be able to start from scratch. ALL BECAUSE I WANTED MOTION CONTROLS IN DOLPHIN

**Comment by xXGamerAwesomeXx** [comment]
had to reinstall windows but luckily it saved all the files
