### ISSUE TITLE
Major input lag

### ISSUE THREAD

**Issue by pinkpotato401** [Davidobot/BetterJoyForCemu#143]
At first i thought i didn't set up betterjoyforcemu correctly, however, it turns out input lag is around 2 seconds. LOZ;BOTW is unplayable. The input lag occurs in both joycons. i have tried putting in the controllers in different orders as another user suggested, it did not work. sometimes it seems to work without input lag for a few seconds, after that it returns to it's unbearable 2 second delays.

**Comment by Shinwoir** [comment]
I've had the same problems, at the beginning it seems fine but then I'm having like 2 seconds input lag

**Comment by Serpens66** [comment]
I have the ame problem with joycons, it works without any problems for a minute and then again 30 seconds with 1-2 seconds delay. Then works again and so on, it is kind of random.
Can this be fixed?
