### ISSUE TITLE
Broken face button layout

### ISSUE THREAD

**Issue by MemesDank456** [Davidobot/BetterJoyForCemu#168]
When I used this I expected the buttons be mapped so A=A, B=B, X=X and Y=Y, but I noticed that instead its A=B, B=A, X=Y, and Y=X. I can deal with it in Cemu because I can map the controls, but when I use Windows 10's Game Bar, I keep pressing A to select something like the Screen Recording option, but it registers as B, causing me to exit the menu. And its a bigger problem in games where you can't map the controls

**Comment by v5tge** [comment]
They are mapped using the xbox layout. There is an option inside the betterjoyforcemu app that let you change it so the layout match with the one that nintendo uses. It uses the xbox one by default because most people use to play with xbox controllers, so this way it feels the same unless you need to look for the button, something that anyone does. The steam drivers works like this too.

**Comment by MemesDank456** [comment]
How do I set it to use the Nintendo layout? I don't see any options in the app

**Comment by v5tge** [comment]
Im not on the pc right now, but if you open the app, an arrow should appear at the right side. That opens a menu with a lot of options, one of them to switch a-b and another one to switch x-y

**Comment by MemesDank456** [comment]
Nope. No arrow

**Comment by v5tge** [comment]
What version are you using?

**Comment by MemesDank456** [comment]
the latest version

**Comment by MemesDank456** [comment]
uhh now it doesn't let me open the app. every time I open it it just crashes with the message:

Pro Controller connected
Pro Controller connected

**Comment by v5tge** [comment]
Try the nightly v6, it works fine, and you can check the readme to see in screenshots the arrow i was talking about. Also under changelog you can see that one of the changes is related to this

**Comment by MemesDank456** [comment]
ok, I'll try that

**Comment by v5tge** [comment]
Let me know if you get it to work

**Comment by MemesDank456** [comment]
It works but I can't seem to open the app without having it stuck in the tray now

**Comment by v5tge** [comment]
I think if the app is running it always appears in the tray. Its a way to know if its running or not. Im not sure if you can remove it, but it works the same way other apps that work in the background do. As an example i have TeamViewer, hamachi, epic games, and similar apps, so i don't think is an error. Anyway if there is no way to remove the system tray icon you can leave a suggestion to add an option or something

**Comment by MemesDank456** [comment]
ok I just rebooted and it works again, thanks for helping!

**Comment by v5tge** [comment]
No problem. I'm glad it works 😉
