### ISSUE TITLE
Not detecting R button

### ISSUE THREAD

**Issue by wax-simulacra** [Davidobot/BetterJoyForCemu#172]
Hi. 
On PC I use only the right JoyCon, I use it in pair with Xpadder to assign shortcuts for Photoshop.
The issue with Betterjoy is that when just the right JoyCon is paired the R button its non-functional, though when both JoyCons are paired the button works fine.
My guess is that because its only one JoyCon it thinks you are gonna use it horizontally and on Switch you dont use those buttons like that, so it doesn't detect that input, weirdly enough ZL still works.

I was using Vjoy along with mfosse joycon driver before and the single JoyCon worked perfectly. Cant use those drivers anymore because Windows 10 updates broke it.
It sucks because Betterjoy its almost perfect for the type of use I give to the JoyCon.

Hope this can be fix in a new update, maybe add the functionality to use the JoyCon vertically without having to pair both, specially because all the inputs (joysticks, xyab buttons) get shifted.
Anyways, thanks.

**Comment by sanjaysatoji** [comment]
I have the same issue in single joycon mode, and the same applies to L on the left joy-con. Would be great if these could be bound to a key

**Comment by wax-simulacra** [comment]
> 
> 
> I have the same issue in single joycon mode, and the same applies to L on the left joy-con. Would be great if these could be bound to a key

Vjoy has been updated to work with Windows again if you still need a working driver.

**Comment by sanjaysatoji** [comment]
thanks I'm using the fosse driver now
