### ISSUE TITLE
Occasional insane input lag on switch pro controller

### ISSUE THREAD

**Issue by martync1234** [Davidobot/BetterJoyForCemu#180]
Whilst using a switch pro controller with both steam and cemu via bluetooth, there are occasions when for minutes at a time there will be insane input lag on the pro controller joysticks, any idea on how to remedy this? it has been an issue for me for multiple builds and I'm currently running it at version 6.0

**Comment by jasonridesabike** [comment]
+1

**Comment by Martijndewin** [comment]
+1
