### ISSUE TITLE
Can't hit apply when trying to add 3rd party controllers

### ISSUE THREAD

**Issue by Longtime4321** [Davidobot/BetterJoyForCemu#182]
I put the 3rd party controller in the switch controllers slot and checked pro controller, (i'm using a faceoff wired pro controller) and hitting apply does nothing

**Comment by numchuk12** [comment]
I'm in the same boat hoping you found a solution. I heard it was because the program only looks for Nintendo VendorID's.

**Comment by MizuRyujin** [comment]
No updates on this issue yet?

**Comment by HughDaniels** [comment]
Using a honson switch pro controller with motion sensor. is it true that this program is such a googer that it excludes all controllers except official nintendont ones!?

same problem hitting apply does nothing. even though driver install and controller works fine outside of the betterjoy program

**Comment by numchuk12** [comment]
I'm going to update this thread for the dev by saying I am using a CORE(plus) controller and the program detects my advice. I humbly request that this device be added properly as I bought this one for CEMU and need the motion controls for certain parts of games. Thank you in advance
