### ISSUE TITLE
Controller not found

### ISSUE THREAD

**Issue by ChickenX99** [Davidobot/BetterJoyForCemu#183]
I've done everything to set up my faceoff Nintendo switch pro controller, but the software doesn't seem to be able to find my controller. I've tried reinstalling the software, restarting my PC, and I've tried older versions of the software but i cant seem to get it to find my controller.

**Comment by ToxicMushroom** [comment]
but those are wired right ?

**Comment by Uxusk1** [comment]
mine is wored!

**Comment by ChickenX99** [comment]
I haven't tried a since I replaced the product with a Nintendo switch pro controller, but last I checked faceoff controllers don't work with this software.
