### ISSUE TITLE
Driver install not working

### ISSUE THREAD

**Issue by dmantheman** [Davidobot/BetterJoyForCemu#188]
I tried the last 3 versions with the newest one being Nightly V6. Everytime I open up the driver install batch and try to run it as admin, the window opens in cmd, and closes right away. This happens on both the 32bit and 64bit versions and I can't install the driver. 

My windows is **Windows 10 Home 64bit Build 17763**

If I run the exe for the app without the driver install then I get a .Net Framework Error upon launching. I've updated to the latest .Net Framework 4.8 and still the same issue.

Not sure what to do. I have seen someone else having this issue on reddit that was never resolved. Any ideas?

**Comment by BoomyKing** [comment]
what file is the driver install in?
