### ISSUE TITLE
Motion Control Issue

### ISSUE THREAD

**Issue by FurrySlayer** [Davidobot/BetterJoyForCemu#235]
I'm also having issues with motion controls in Breath of the Wild. I'm using v6 of BJFC and a Switch Pro Controller, and made sure that Cemu, Cemuhook, and my controller are up to date.
I have the Cemuhook settings as:
[Input]
motionSource = DSU_A438CC22033C
motionSourceIsBtnSource = false
serverIP = 127.0.0.1
serverPort = 26760

I make sure to run BJFC before starting Cemu. So, I checked some of the other posts with similar issues to mine, and I found out that the motion controls do indeed work if I use PadTest, but when I try using them in the game, they just won't work. I've tried changing the port numbers in both BJFC and Cemuhook to no avail and have turned my controller off and on while BJFC is running. That also didn't work.
I feel like it may be an issue with the game. I have the latest update and DLC. The controller's motion source is detected, but it doesn't actually do anything in-game. I don't know what to do anymore.

**Comment by Pestudkaru** [comment]
I have the same problem. I tried Switch Pro controller with BJFC and everything works except the motion controls. I also tried DS4windows and the same issue. No motion controls. Maybe it's a Cemu issue?

**Comment by Pestudkaru** [comment]
I got it working but I don't know what was the problem (possibly the port issue). I re-downloaded Cemu (1.17.2), cemuhook and BJFC. I manually changed BJFC port to 26761 edited the .ini file and added just this one line:  serverPort = 26760.
Restarted my computed several times and made sure to start BJFC first then Cemu. Did the button mapping and then it worked. So happy! ^_^
