### ISSUE TITLE
System wide Rumble

### ISSUE THREAD

**Issue by gssci** [Davidobot/BetterJoyForCemu#25]
Helllo there,
great work on this one. This is definitely my favorite Pro Controller and Joycon drivers, worked flawlessly right after download. However, there is a feature I would like to request. I'm using the controller on Dolphin 5.0, however the rumble motors are not working with it. Could it be possible for you to implement a system wide "standard" rumble feature? 
Thank you so much anyway for this piece of software

**Comment by legoj15** [comment]
Dolphin 5.0 has an issue where the motors don't rumble on the input screen, which was addressed by the devs in a recent dev build. I can use the motors fine on my system with dolphin

**Comment by gssci** [comment]
Alright! Thanks for the tip
