### ISSUE TITLE
Can't get Cemu to see motion controls for Switch Pro Controller

### ISSUE THREAD

**Issue by seanbperiod** [Davidobot/BetterJoyForCemu#36]
Trying to get this setup but under GamePad Motion Source, it always says DSU: DISCONNECTED

Running 1.11.3, Betterjoy v4 and cemuhook 0.5.6.4

I ran pad test and it was able to see the motion controller working.

Cemu Input Settings are set to a profile, and I can configure the buttons and rumble there with input/feedback from controller. 

In BetterJoy the server is set at 127.0.0.1:26760

And cemuhook.ini is 

[Input]
motionSourceIsBtnSource = true
serverIP = 127.0.0.1
serverPort = 26760

What am I missing?

**Comment by AtomicStryker** [comment]
Mine looks like this

[Input]
motionSource = DSU1
motionSourceIsBtnSource = false
serverIP = 127.0.0.1
serverPort = 26760
