### ISSUE TITLE
Can we get to emulate only gyro?

### ISSUE THREAD

**Issue by rsilva48** [Davidobot/BetterJoyForCemu#40]
So I wanted to know if it's posible to make BetterJoyForCemu to only emulate the gyro, disabling the xinput emulation, just sending the motion data to the server

**Comment by legoj15** [comment]
Use BetterJoy v3 then, it does exactly that. Also, I think the latest commit is working on that for possibly a future release.

**Comment by rsilva48** [comment]
thanks! actually v2 is the one that just does that, v3 is the one that starts xinput emulation, but v2 doesnt have the fancy features like the gui or to minimize to the taskbar, hopefully we get those features with a future release, I just saw HID guardian in the commit, my bad
