### ISSUE TITLE
Joycon act like Mouse/Keyboard

### ISSUE THREAD

**Issue by JajoDeBudiBub** [Davidobot/BetterJoyForCemu#41]
I've been trying to map the buttons for cemu but they wont show up and my joycon act like a mouse and keyboard.

**Comment by legoj15** [comment]
do you have Steam open?

**Comment by JajoDeBudiBub** [comment]
No but I just put cemu in fullscreen so I dont close anything.

**Comment by legoj15** [comment]
Now that's weird. The only reason I asked is because Steam makes the Pro Controller act like a mouse and keyboard when it's open. Maybe @Davidobot knows what's going on?

**Comment by SmokePuddingEveryday** [comment]
Late response but use JoyToKey
