### ISSUE TITLE
A Problem with server communications. Or... something

### ISSUE THREAD

**Issue by KevinTejada** [Davidobot/BetterJoyForCemu#7]
Every time I have launched the application, it has always recognized my Joycons and synced them as one controller. However, They do not register as controllers on Cemu and I am pretty sure it pertains to the fact that the application is not able to "start the server", for whatever reason. If you guys have any possible solutions please contact me, it'll be much appreciated.

**Comment by MathBurns** [comment]
Maybe I'm wrong but cemu isn't supposed to recognize your joycons. You just have to launch the app. If it detects your joycons, launch cemu. Make sure that in your input settings, your controller 1 is set as Wii U gamepad and leave the rest empty.  After that open the option tab and go to gamepad motion source. You should see DSU1: "Mac address or something". Select it and choose by slot or by mac(I don't know if it makes a difference) and also make sure the Also use for buttons/axes is ticked on at the bottom (that's what makes the joycons work. You don't need to set up what buttons do, it's done automatically. From there you launch a game and it should work

**Comment by KevinTejada** [comment]
Perhaps I wasn't specific on which application I was talking about. I'm aware that Cemu is not designed to sync Joycons, but what I'm saying is that the "BetterJoyforCemu" app is not registering my Joycons as controllers for Cemu like it's supposed to. The "BetterJoyforCemu" app recognizes both of my Joycons, but then it tells me that it cannot start a server, whatever that means. That's where my problem lies.

**Comment by KevinTejada** [comment]
Nevermind, I have just fixed the problem. I had WiinUSoft open this whole time without me noticing. lolololol
