### ISSUE TITLE
Running as admin

### ISSUE THREAD

**Issue by Wubly** [Davidobot/BetterJoyForCemu#70]
I try running the .bat file as admin but it doesn't recognize it.

**Comment by LoneGhostOne** [comment]
I ran into a similar issue and could only fix it by switching from trying to run the x64 bit version to the x32 bit version.

**Comment by Wubly** [comment]
ho

**Comment by Wubly** [comment]
how do you get the 32 bit version
i know thats the problem now, my computer is 32 bit but how you get it
